service: laravel-serveless-schedule-test

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: us-east-1
    profile: 211125325981_AdministratorAccess
    # Environment variables
    environment:
      APP_ENV: ${sls:stage}
      APP_KEY: ${ssm:/sandbox/serverless-schedule-test/app-key}
      SESSION_DRIVER: cookie
      DB_CONNECTION: mysql
      SQS_QUEUE: arn:aws:lambda:us-east-1:211125325981:function:laravel-serveless-test-dev-jobsWorker
      QUEUE_CONNECTION: sqs
      DB_HOST: laravel-serveless-test-dev-mysqlrdsinstance-4kfgcokwbn32.cxuuquyy2ebh.us-east-1.rds.amazonaws.com
      DB_USERNAME: ${ssm:/sandbox/serverless-test/rds-username}
      DB_PASSWORD: ${ssm:/sandbox/serverless-test/rds-password}
      DB_DATABASE: ${ssm:/sandbox/serverless-test/rds-dbname}
      AWS_BUCKET: serverless-test-s3-bucket
      FILESYSTEM_DISK: s3
      CUSTOM_AWS_ACCESS_KEY_ID: ${ssm:/sandbox/serverless-test/aws-access-key}
      CUSTOM_AWS_SECRET_ACCESS_KEY: ${ssm:/sandbox/serverless-test/aws-secret-access-key}
      CUSTOM_AWS_DEFAULT_REGION: us-east-1

    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - 's3:*'
        Resource:
          - 'arn:aws:s3:::serverless-test-s3-bucket'

package:
    # Files and directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'
        - '!docker/**'
        - '!.env'

functions:

    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        runtime: php-82-fpm
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - httpApi: '*'

    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        runtime: php-82-console
        timeout: 720 # in seconds

    sns:
      handler: App\Services\SNSHandler
      runtime: php-82-console
      events:
        - sns:
            arn: arn:aws:sns:us-east-1:211125325981:UserEvents

plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref
    - serverless-lift
