service: laravel-serveless-schedule-test

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: us-east-1
    profile: s3_serverless_test_user
    # Environment variables
    environment:
      APP_ENV: ${sls:stage}
      APP_KEY: ${ssm:/sandbox/serverless-schedule-test/app-key}
      SESSION_DRIVER: cookie
      DB_CONNECTION: mysql
      SQS_PREFIX: !Join
        - ""
        - - "https://sqs."
          - !Ref "AWS::Region"
          - ".amazonaws.com/"
          - !Ref "AWS::AccountId"
          - "/"
          - "laravel-serveless-test-dev-jobs"
      QUEUE_CONNECTION: sqs
      DB_HOST: laravel-serveless-test-dev-mysqlrdsinstance-4kfgcokwbn32.cxuuquyy2ebh.us-east-1.rds.amazonaws.com
      DB_USERNAME: ${ssm:/sandbox/serverless-test/rds-username}
      DB_PASSWORD: ${ssm:/sandbox/serverless-test/rds-password}
      DB_DATABASE: ${ssm:/sandbox/serverless-test/rds-dbname}
      AWS_BUCKET: serverless-test-s3-bucket
      FILESYSTEM_DISK: s3

    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - 's3:ListBucket'
          - 's3:GetObject'
        Resource:
          - 'arn:aws:s3:::serverless-test-s3-bucket'
          - 'arn:aws:s3:::serverless-test-s3-bucket/*'
      - Effect: 'Allow'
        Action:
          - 'ssm:GetParameters'
          - 'ssm:GetParameter'
          - 'ssm:GetParametersByPath'
        Resource:
          - 'arn:aws:ssm:us-east-1::parameter/*'
      - Effect: "Allow"
        Action:
          - 'sqs:SendMessage'
          - 'sqs:GetQueueUrl'
          - 'sqs:ReceiveMessage'
          - 'sqs:DeleteMessage'
        Resource:
          - 'arn:aws:sqs:us-east-1:211125325981:laravel-serveless-test-dev-jobs'

package:
    # Files and directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'
        - '!docker/**'
        - '!.env'

functions:

    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        runtime: php-82-fpm
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - httpApi: '*'
            - sqs:
                arn: arn:aws:sqs:us-east-1:211125325981:laravel-serveless-test-dev-jobs

    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        runtime: php-82-console
        timeout: 720 # in seconds

    sns:
      handler: App\Handlers\SNSHandler
      runtime: php-82
      timeout: 28
      events:
        - sns:
            arn: { "Fn::Join" : ["", ["arn:aws:sns:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":UserEvents" ] ]  }
            topicName: UserEvents
            filterPolicy:
              MessageType:
                - ScheduleLoaded

plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref
    - serverless-lift
